# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed text)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$maven\
$nim\
$nodejs\
$bun\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[◎](bold italic yellow)"
error_symbol = "[○](italic mauve)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic mauve"
symbol = " "
disabled = false

[username]
style_user = "yellow bold italic"
style_root = "mauve bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = " "
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold blue)'

[cmd_duration]
format = "[◄ $duration ](italic text)"

[jobs]
format = "[$symbol$number]($style) "
style = "text"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold mauve)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed text"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed mauve"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = " "
style = "italic blue"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic mauve)"
ahead = "[▴│[${count}](bold text)│](italic green)"
behind = "[▿│[${count}](bold text)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular text)│▿┤[${behind_count}](regular text)│](italic mauve)"
untracked = "[◌◦](italic yellow)"
stashed = "[◃◈](italic text)"
modified = "[●◦](italic yellow)"
staged = "[▪┤[$count](bold text)│](italic sapphire)"
renamed = "[◎◦](italic blue)"
deleted = "[✕](italic red)"

[deno]
format = " [deno](italic) [ $version](green bold)"
version_format = "${raw}"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = " "
style = "bold yellow"

[nodejs]
format = " [node](italic) [ ($version)](bold green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[bun]
format = " [bun](italic) [ ($version)](bold green)"
version_format = "${raw}"

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "󰏗 "
style = "dimmed yellow italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = " "
style = "bold red"
version_format = "${raw}"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = " "

[buf]
symbol = " "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[pixi]
symbol = "󰏗 "
format = " pixi [$symbol$version ($environment )]($style)"

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = " "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = " "
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed text)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed yellow)'

[spack]
symbol = " "
format = " spack [$symbol$environment]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
